---
name: Run checks

on:
  push:
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies (non-strict)
        run: pnpm install --no-frozen-lockfile

      - name: Run checks
        run: pnpm check
